### ISSUE TITLE
Plugin settings page design

### ISSUE THREAD

**Issue by puzhu** [OnlyEver/onlyever_obsidian_sync#11]
Few things to implement on the Obsidian plugin settings page

- [x] User needs to submit the API key. This should trigger a check to establish that the token is correct. Maybe we add a checkmark next to the token if it is correct? And a red X if it is incorrect?
- [x] Add a toggle to hide and unhide the API key token
![Screen Shot 2023-07-12 at 12 38 28 PM](https://github.com/OnlyEver/onlyever_obsidian_sync/assets/6342432/8fbd6faf-5251-411b-896d-9a94bf101230)

**Comment by sriza** [comment]
Icon, toggle and error message are added to the plugin settings page.
The fixes to this issue can be seen on release v1.3.1.
