### ISSUE TITLE
Add option to delete a note that I own

### ISSUE THREAD

**Issue by puzhu** [OnlyEver/onlyever_obsidian_sync#15]

**Comment by praweshsth** [comment]
When user deletes a note, it will delete from global_source and it will not be accessible to other users if it was published and added to other's library. But show confirmation message to user before deleting as below:

If the note is not added in other's library - 'Are you sure you want to delete the note?'
If the note is added in other's library - 'Are you sure you want to delete this note? Other users are using this note.'

Your thoughts on this @puzhu

**Comment by puzhu** [comment]
1. "Are you sure?"
2. "X users will lose access to this note. Are you sure?"

**Comment by Shreedhar73** [comment]
#126
#139

merged
