### ISSUE TITLE
Develop obsidian plugin to sync the notes to only ever app

### ISSUE THREAD

**Issue by praweshsth** [OnlyEver/onlyever_obsidian_sync#2]
- [ ] user can sync notes from obsidian using a YAML (frontmatter) property
- [ ] plugin should monitory the mtime for files to trigger sync when notes are updated in obsidian
- [ ] Changing the note title in obsidian triggers a change to the file name in Obsidian, the sync operation should maintain link even if the file name on Obsidian is updated
- [ ] if a note is deleted then the notes in only ever should also be deleted
- [ ] If a note contains an internal link to another note, which is not published, then that internal link shouldn't be sent to only ever but only the text. (This could be done using app logic instead of plugin - we check if source exists and it does then we render else we don't)

  - user should be able to search for obsidian plugin in community plugins of obsidian (we don't need this during the current phase)
- use existing plugins for development (@puzhu)

**Comment by sriza** [comment]
New version of Only Ever v1.2.0 contains:
- [x] update of plugin name to 'Only Ever'
- [x] sync of note on initial load
- [x] colored icons to identify if the plugin token is correct or not
- [x]  frontmatter removed from content of file during sync
- [x] identification of network error and display of notice based on it

To solve the issue of **network unavailability**, a **scheduled sync** is implemented. The scheduled sync collects all the user file with 'oe_sync: true' frontmatter for **every hour** and makes API call to sync those notes. The notes which were modified after their previous sync will then be updated to the database.


The user notes are now synced:
- on loading of Obsidian
- everytime modification on the file is made
- during the scheduled sync that occurs every hour.
