### ISSUE TITLE
Sync is having trouble updating articles

### ISSUE THREAD

**Issue by puzhu** [OnlyEver/onlyever_obsidian_sync#23]
I set up sync on a new obsidian vault and updates seem to be getting truncated. Only part of the file is visible on only ever.

**Comment by puzhu** [comment]
![Screenshot 2023-09-14 at 4 00 16 AM](https://github.com/OnlyEver/onlyever_obsidian_sync/assets/6342432/d416cd40-00e2-42a4-8403-0ce17c15ef8c)

This is a side by side comparison of the two.

**Comment by PG-Momik** [comment]
@puzhu, here's a summary of this issue:

### Issue
The content of notes is only partially syncing.

---

### Cause
Recent changes made in PR: #22, to extract and parse outgoing_links, caused this issue to surface. Specifically, the code responsible for parsing the content to replace default links with OE internal links would disregard content that came after the final link. As a result, only a portion of the content was being synced. 
In your case, contents after `[[collection]]` were ignored.

---

### Solution
We've fixed the logic in the code responsible for parsing internal links. The changes are in PR: #24. These updates have been implemented in v1.3.5, so please ensure that you reinstall v1.3.5.

---
Please let us know if the issue persists or you encounter any further problems.

**Comment by puzhu** [comment]
Thanks
