### ISSUE TITLE
Headings are not being rendered correctly

### ISSUE THREAD

**Issue by puzhu** [OnlyEver/onlyever_obsidian_sync#25]
![Screenshot 2023-09-15 at 10 24 12 AM](https://github.com/OnlyEver/onlyever_obsidian_sync/assets/6342432/41a65eb5-7d42-4444-8ec9-dad3293313e1)

**Comment by PG-Momik** [comment]
@puzhu, we've confirmed that this is an app level issue and has been forwarded to the mobile team and has been solved. Please let us know if the issue persists in the next apk build.
