### ISSUE TITLE
BRAT Implementation

### ISSUE THREAD

**Issue by sriza** [OnlyEver/onlyever_obsidian_sync#9]
BRAT is an obsidian plugin that enables beta testing of obsidian plugin. Implementation of brat allows creation of beta plugin thus enabling reviewing and testing of plugin.

**Tasks**

- [x] Implementation of BRAT in obsidian plugin
- [x] Testing obsidian plugin in mobile and desktop obsidian application

**Comment by praweshsth** [comment]
Video on how to install sync plugin in obsidian using BRAT:


https://github.com/OnlyEver/onlyever_obsidian_sync/assets/2421695/5d7b1948-2064-49ea-bc5c-ce02fb50dda0

**Comment by sriza** [comment]
Completed and merged to main branch
